#!/usr/bin/env bash
#Pipeline for running and organizing output from PHoeNIx

#Make sure PHoeNIx and Kraken2 are installed on your computer, and make sure you have the Standard-08 database installed in /kraken2-master/Standard-08

#Make a directory called "reads" within your Kraken2 directory
##Within the "reads" directory, make a sub-directory for each sample
##Each sample sub-directory should include ONLY the 2 fastq files

#Output will be in output.tsv in /kraken2-master/results
##Make sure there is not already a file called output.tsv in that directory

#Working directory must be your Kraken2 directory

#Before starting, activate your phoenix Conda environment (conda activate phoenix)

#Edit script so paths are correct for your computer:

samplesheet=/home/mdungsmain/Janis/Programs/Kraken2/kraken2-master/samplesheet.csv
output=/home/mdungsmain/Janis/Programs/Kraken2/kraken2-master/results/output.csv
home=/home/mdungsmain/Janis/Programs/Kraken2/kraken2-master/

cd $home

#Create the sample sheet
printf "sample,fastq_1,fastq_2\n" > $samplesheet
cd reads/

#Add each sample to the sample sheet
for dir in */
do
	cd $dir
	echo "$dir" | cut -d/ -f1 | tr -d '\n' >> $samplesheet
	for file in *
	do
		printf "," >> $samplesheet
		realpath ${file} | tr -d '\n' >> $samplesheet
	done
	printf "\n" >> $samplesheet
	cd ..
done

cd $home

#Run PHoeNIx
nextflow run phoenix/main.nf -profile docker -entry PHOENIX --kraken2db ./Standard-08 --input $samplesheet

#Organize the output 
cd results/
for dir2 in */
do 
	printf "${dir2}" >> $path_to_output
	printf "\n\n" >> $path_to_output
	cd $dir2
	cat *summaryline.tsv >> $path_to_output
	printf "\n\n" >> $path_to_output
	cat *synopsis >> $path_to_output
	printf "\n\n" >> $path_to_output
	cd ANI/
	cat *fastANI.txt >> $path_to_output
	printf "\n\n" >> $path_to_output
	cd ..
	cd AMRFinder/
	cat *all_genes.tsv >> $path_to_output
	printf "\n\n\n\n" >> $path_to_output
	cd ..
done


