#!/usr/bin/env bash
#Pipeline for bacterial analysis using Conda; trimming, assembly, species identification, and AMR genes (based on 3 databases)
#Output will be in output.tsv
#Run in directory with the fastq.gz files from one sample (i.e. just one R1 file and one R2 file) 
#Run fastani with reference fasta once MLST determines likely species

#Activate Conda environment before running!! conda activate bacterial

#Identify fastq files
file1='*R1*.fastq.gz'
file2='*R2*.fastq.gz'
#Trimming
trimmomatic PE -threads 16 $file1 $file2 p1.fq.gz up1.fq.gz p2.fq.gz up2.fq.gz ILLUMINACLIP:TruSeq3-PE.fa:2:30:10:2:keepBothReads LEADING:3 TRAILING:3 MINLEN:36
#Identify trimmed fastq files
file3='p1.fq.gz'
file4='p2.fq.gz'
#Assembly
spades -1 $file3 -2 $file4 -o .
#Identify fasta file
file5='contigs.fasta'
#Species identification
mlst $file5 >> output.tsv
#Identification of AMR genes
abricate $file5 --db ncbi >> output.tsv
abricate $file5 --db card >> output.tsv
abricate $file5 --db resfinder >> output.tsv
abricate $file5 --db plasmidfinder >> output.tsv

