#!/usr/bin/env bash
#Pipeline for bacterial analysis using Conda; trimming, assembly, species identification, and AMR genes
#Run in directory with a sub-directory for each set of fastq.gz files (i.e. just one R1 file and one R2 file in each directory); the name of each directory should contain the LIMS ID of the sample
#Output will be in output.tsv
#Run fastani with reference fasta once MLST determines likely species

for dir in */
do
	cd $dir
	#Trimming
	staphb-tk trimmomatic PE -threads 16 *R1*.fastq.gz *R2*.fastq.gz p1.fq.gz up1.fq.gz p2.fq.gz up2.fq.gz ILLUMINACLIP:TruSeq3-PE.fa:2:30:10:2:keepBothReads LEADING:3 TRAILING:3 MINLEN:36
	#Assembly
	staphb-tk spades -1 p1.fq.gz -2 p2.fq.gz -o .
	#Species identification
	printf "${dir}" | cut -d / -f 1 >> output.tsv
	printf "\n\nSpecies identification\n" >> output.tsv
	staphb-tk mlst contigs.fasta >> output.tsv
	#Identification of AMR genes
	printf "\n\n\nAMR Genes Identified\n\n"
	printf "\nNCBI database\n" >> output.tsv
	staphb-tk abricate contigs.fasta --db ncbi >> output.tsv
	printf "\nCARD database\n" >> output.tsv
	staphb-tk abricate contigs.fasta --db card >> output.tsv
	printf "\nResfinder database\n" >> output.tsv
	staphb-tk abricate contigs.fasta --db resfinder >> output.tsv
	printf "\nPlasmidfinder database\n" >> output.tsv
	staphb-tk abricate contigs.fasta --db plasmidfinder >> output.tsv
	#Summary
	printf "\nSummary of AMR Genes of Interest (KPC, NDM, OXA, VIM, IMP) \n" >> output.tsv
	awk -F"\t"  '$6 ~ "KPC" || $6 ~ "kpc" || $6 ~ "NDM" || $6 ~ "ndm" || $6 ~ "OXA" || $6 ~ "oxa" || $6 ~ "VIM" || $6 ~ "vim" || $6 ~ "IMP" || $6 ~ "imp" {printf $6 "\n"}' output.tsv >> output.tsv
	cd ..
done


