#!/usr/bin/env bash
#Pipeline for running and organizing output from PHoeNIx

#Make sure PHoeNIx is installed in .../kraken2/phoenix
#Make sure you have the Standard-08 database installed in .../kraken2/Standard-08

#Make a directory called "reads" within your Kraken2 directory
##Within the "reads" directory, make a sub-directory for each sample (the directory name should be the sample name)
##Each sample sub-directory should include ONLY the 2 fastq files (each fastq file should have the sample name before any underscore in the file name)

#Before starting, activate your PHoeNIx Conda environment (i.e. conda activate phoenix or whatever you named it)

#Edit script so paths are correct for your computer:
#home: the location of your kraken2 directory
home=/mnt/data/kraken2/
#samplesheet: the location where your samplesheet will be created and what it will be named
samplesheet=/mnt/data/kraken2/samplesheet.csv
#summary: the location where your QC summary file will be created and what it will be named
summary=/mnt/data/kraken2/phx_output/summary.tsv
#output directory: the location where your output file will be created and what it will be named
output=/mnt/data/kraken2/phx_output/

cd $home

#Create the sample sheet
printf "sample,fastq_1,fastq_2\n" > $samplesheet
cd reads/

#Add each sample to the sample sheet
for dir in */
do
	cd $dir
	echo "$dir" | cut -d/ -f1 | tr -d '\n' >> $samplesheet
	for file in *
	do
		printf "," >> $samplesheet
		realpath ${file} | tr -d '\n' >> $samplesheet
	done
	printf "\n" >> $samplesheet
	cd ..
done

cd $home

#Run PHoeNIx
nextflow run ./phoenix/main.nf -profile docker -entry PHOENIX --kraken2db ./Standard-08 --input $samplesheet

#Assemble the output 
cd $output
echo "PHoeNIx Output" > $output
cat Phoenix_Summary.tsv > $output
printf "${dir}\n\n" >> $summary
for dir in */
do 
	printf "${dir}\n\n" >> $summary
	cd ${dir}
	cat *synopsis* >> $summary
	cat *Assembly_ratio* >> $summary
	printf "\n\n" >> $summary
	cd ANI/
	cat *fastANI* >> $summary
	printf "\n\n" >> $summary
	cd ..
	cd qc_stats/
	cat *trimmed_read* >> $summary
	printf "\n\n" >> $summary
	cd ..
	cd AMRFinder/
	cat *all_genes* >> $summary
	printf "\n\n" >> $summary
	cd $output
done



