#!/usr/bin/env bash
#Pipeline for running and organizing output from Cecret

#Make a directory called "reads" within your Cecret directory
##Within the "reads" directory, make a sub-directory for each sample (the directory name should be the sample name)
##Each sample sub-directory should include ONLY the 2 fastq files (each fastq file should have the sample name before any underscore in the file name)

#Edit script so paths are correct for your computer:
#home: the location of your cecret directory
home=/home/mdungsmain/Janis/Programs/Cecret
#samplesheet: the location where your samplesheet will be created and what it will be named
samplesheet=/home/mdungsmain/Janis/Programs/Cecret/samplesheet.csv

cd $home

#Create the sample sheet
printf "sample,fastq_1,fastq_2\n" > $samplesheet
cd reads/

#Add each sample to the sample sheet
for dir in */
do
	cd $dir
	echo "$dir" | cut -d/ -f1 | tr -d '\n' >> $samplesheet
	for file in *
	do
		printf "," >> $samplesheet
		realpath ${file} | tr -d '\n' >> $samplesheet
	done
	printf "\n" >> $samplesheet
	cd ..
done

cd $home

#Run Cecret
nextflow run main.nf -c configs/docker.config --sample_sheet ./samplesheet.csv

#Concatenate the consensus sequences
cd consensus/
cat *.fa > all_sequences.fasta
